- id: 1
  name: ethereum
  symbol: ETH
  etherscan_api_key: "CQZEXX84G6AQ5R8AZCII626EA43VPNJEEU"
  chain: 'ropsten' # one of mainnet, kovan, ropsten, rinkeby
  exchange_address_priv: "2f832c0c03c67d344f110df6ae37daf8181db66eb1efad3e63cfe55c2029a02c"
#  exchange_address_priv: "c4a80d0a5a6ca72d75296ef7193541a7f27eb0face176570c9e580559b273906"
  address_contract_address: "0x826c6ee06c89b2f8ceb39ebc3153a6e7553a2ebe"
  gas_limit: 200000
  gas_price: 20000000000 # 20gwei
- id: 2
  name: status
  symbol: SNT
- id: 3
  name: attention
  symbol: ATM