# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c1c9a5849577e069b381da19257400d5eef768c75b041cd4618bb2c9fc6959de4add8ccc77e274268b447bcb6c57f45c9e0fce17860718b163db84cb12948d69

test:
  secret_key_base: 3c41161d22b88c8a8c6aed7dbeb788370a96e15baa062877157ca33defe6e698fcdd852c789ec5c769f432c3a7cf5b23e8cadb4218ddec47e144bafb36d4e36e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
